# 🐼 Taller Práctico de Pandas y Operaciones Matemáticas
**Taller de Inteligencia Artificial (Librería Pandas) — Corte II**  
**Programa:** Ingeniería de Sistemas — Universidad del Pacífico  
**Semestre:** 8 | **Fecha:** 25/05/2026

**Integrantes**: Jefferson Manuel Valencia Riascos

Isnildo Equia Perteaga

Sebastian Rojas Cabrera

Yeison Stiven Lozano angulo

---
**Objetivo:** Aplicar los conceptos fundamentales de análisis de datos utilizando la librería Pandas en Python, realizando operaciones matemáticas, estadísticas y manipulación de columnas.

## 📦 Importación de librerías

In [3]:
import pandas as pd
import numpy as np

print('✅ Librerías importadas correctamente')
print(f'   → Pandas versión: {pd.__version__}')
print(f'   → NumPy versión:  {np.__version__}')

✅ Librerías importadas correctamente
   → Pandas versión: 2.2.2
   → NumPy versión:  2.0.2

---
## 🗃️ Carga del Dataset

El dataset `productos.csv` se encuentra en github al cual podremos acceder a el usando el siguiente comando:

In [4]:
url = 'https://raw.githubusercontent.com/jeffer301/INTELIGENCIA-ARTIFICIAL--JEFFERSON-VALENCIA/refs/heads/main/taller-panda/productos.csv'
df = pd.read_csv(url, encoding='utf-8-sig')

print(f'✅ Dataset cargado exitosamente')
print(f'   → Filas    : {len(df)}')
print(f'   → Columnas : {list(df.columns)}')

✅ Dataset cargado exitosamente
   → Filas    : 60
   → Columnas : ['Producto', 'Precio', 'Cantidad', 'Costo_Envio', 'Categoria']

---
## 📌 Punto 1 — Creación y Exploración del DataFrame

In [22]:
# ── 1.1 Primeras 5 filas ─────────────────────────────────────────────────────
print('=' * 60)
print('📋 PRIMERAS 5 FILAS')
print('=' * 60)
display(df.head(5))

============================================================
📋 PRIMERAS 5 FILAS
============================================================

,Producto,Precio,Cantidad,Costo_Envio,Categoria,Total_Venta,Costo_Total,IVA,Ganancia_Estimada,Perdida_Estimada,Porcentaje_Ventas
0,Laptop,3500000,4,50000,Tecnología,14000000,14050000,2660000.0,3500000.0,7000.0,4.723187
1,Mouse,80000,15,10000,Tecnología,1200000,1210000,228000.0,300000.0,600.0,0.404845
2,Teclado,120000,10,12000,Tecnología,1200000,1212000,228000.0,300000.0,600.0,0.404845
3,Silla,450000,5,30000,Oficina,2250000,2280000,427500.0,562500.0,1125.0,0.759084
4,Escritorio,900000,3,40000,Oficina,2700000,2740000,513000.0,675000.0,1350.0,0.910900

In [6]:
# ── 1.2 Últimas 10 filas ─────────────────────────────────────────────────────
print('=' * 60)
print('📋 ÚLTIMAS 10 FILAS')
print('=' * 60)
display(df.tail(10))

============================================================
📋 ÚLTIMAS 10 FILAS
============================================================

                     Producto   Precio  Cantidad  Costo_Envio   Categoria
50                 UPS 1200VA   350000         7        14000  Tecnología
51           Teclado Mecánico  1300000        22        38000  Tecnología
52           Mouse Ergonómico    95000        18         8000  Tecnología
53               Mouse Gaming   150000        16        10000  Tecnología
54        Monitor 27 pulgadas   280000         5        12000  Tecnología
55  Monitor Curvo 32 pulgadas   450000         4        18000  Tecnología
56               Laptop Gamer   150000         2        10000  Tecnología
57           Laptop Ultrabook  1500000         3        55000  Tecnología
58                    Mini PC  2100000         8        60000  Tecnología
59             Raspberry Pi 4  4800000        14        70000  Tecnología

In [7]:
# ── 1.3 Tipo de dato de cada columna ─────────────────────────────────────────
print('=' * 60)
print('🔍 TIPOS DE DATOS POR COLUMNA')
print('=' * 60)
print(df.dtypes)
print()
print('💡 Interpretación:')
print('   • object  → texto (cadena de caracteres)')
print('   • int64   → número entero de 64 bits')
print('   • float64 → número decimal de 64 bits')

============================================================
🔍 TIPOS DE DATOS POR COLUMNA
============================================================
Producto       object
Precio          int64
Cantidad        int64
Costo_Envio     int64
Categoria      object
dtype: object

💡 Interpretación:
   • object  → texto (cadena de caracteres)
   • int64   → número entero de 64 bits
   • float64 → número decimal de 64 bits

In [8]:
# ── 1.4 Tamaño del DataFrame ─────────────────────────────────────────────────
filas, columnas = df.shape
print('=' * 60)
print('📐 TAMAÑO DEL DATAFRAME')
print('=' * 60)
print(f'   • Filas    : {filas}')
print(f'   • Columnas : {columnas}')
print(f'   • Total celdas: {filas * columnas}')

============================================================
📐 TAMAÑO DEL DATAFRAME
============================================================
   • Filas    : 60
   • Columnas : 5
   • Total celdas: 300

In [9]:
# ── 1.5 Descripción estadística general ──────────────────────────────────────
print('=' * 60)
print('📊 DESCRIPCIÓN ESTADÍSTICA GENERAL')
print('=' * 60)
display(df.describe())
print()
print('💡 Interpretación de las métricas:')
print('   • count  → cantidad de valores no nulos')
print('   • mean   → promedio de los valores')
print('   • std    → desviación estándar (dispersión de los datos)')
print('   • min    → valor mínimo')
print('   • 25%    → primer cuartil')
print('   • 50%    → mediana (valor central)')
print('   • 75%    → tercer cuartil')
print('   • max    → valor máximo')

============================================================
📊 DESCRIPCIÓN ESTADÍSTICA GENERAL
============================================================

             Precio   Cantidad   Costo_Envio
count  6.000000e+01  60.000000     60.000000
mean   6.452500e+05   9.883333  23616.666667
std    8.331752e+05   6.186622  15462.465945
min    2.500000e+04   2.000000   5000.000000
25%    1.575000e+05   5.000000  12000.000000
50%    3.500000e+05   8.000000  18000.000000
75%    8.100000e+05  14.000000  32750.000000
max    4.800000e+06  30.000000  70000.000000

💡 Interpretación de las métricas:
   • count  → cantidad de valores no nulos
   • mean   → promedio de los valores
   • std    → desviación estándar (dispersión de los datos)
   • min    → valor mínimo
   • 25%    → primer cuartil
   • 50%    → mediana (valor central)
   • 75%    → tercer cuartil
   • max    → valor máximo

---
## 📌 Punto 2 — Operaciones Matemáticas entre Columnas

In [10]:
# ── 2.1 Total_Venta = Precio × Cantidad ──────────────────────────────────────
df['Total_Venta'] = df['Precio'] * df['Cantidad']

# ── 2.2 Costo_Total = Total_Venta + Costo_Envio ───────────────────────────────
df['Costo_Total'] = df['Total_Venta'] + df['Costo_Envio']

print('✅ Columnas Total_Venta y Costo_Total creadas')
display(df[['Producto', 'Precio', 'Cantidad', 'Costo_Envio', 'Total_Venta', 'Costo_Total']].head(10))

✅ Columnas Total_Venta y Costo_Total creadas

,Producto,Precio,Cantidad,Costo_Envio,Total_Venta,Costo_Total
0,Laptop,3500000,4,50000,14000000,14050000
1,Mouse,80000,15,10000,1200000,1210000
2,Teclado,120000,10,12000,1200000,1212000
3,Silla,450000,5,30000,2250000,2280000
4,Escritorio,900000,3,40000,2700000,2740000
5,Monitor,1100000,6,35000,6600000,6635000
6,Auriculares Bluetooth,280000,8,15000,2240000,2255000
7,Webcam HD,150000,12,12000,1800000,1812000
8,Micrófono USB,200000,7,10000,1400000,1410000
9,Disco Duro Externo 1TB,320000,10,20000,3200000,3220000

In [11]:
# ── 2.3 Promedio de Total_Venta ───────────────────────────────────────────────
promedio_tv = df['Total_Venta'].mean()
print('=' * 60)
print('📊 PROMEDIO DE TOTAL_VENTA')
print('=' * 60)
print(f'   → Promedio: $ {promedio_tv:,.0f}')
print()
print('💡 En promedio, cada producto genera')
print(f'   $ {promedio_tv:,.0f} en ventas totales.')

============================================================
📊 PROMEDIO DE TOTAL_VENTA
============================================================
   → Promedio: $ 4,940,167

💡 En promedio, cada producto genera
   $ 4,940,167 en ventas totales.

In [12]:
# ── 2.4 Producto con MAYOR Total_Venta ───────────────────────────────────────
idx_max      = df['Total_Venta'].idxmax()
producto_max = df.loc[idx_max, 'Producto']
valor_max    = df.loc[idx_max, 'Total_Venta']

# ── 2.5 Producto con MENOR Total_Venta ───────────────────────────────────────
idx_min      = df['Total_Venta'].idxmin()
producto_min = df.loc[idx_min, 'Producto']
valor_min    = df.loc[idx_min, 'Total_Venta']

print('=' * 60)
print('🏆 PRODUCTO CON MAYOR TOTAL_VENTA')
print('=' * 60)
print(f'   → Producto : {producto_max}')
print(f'   → Total    : $ {valor_max:,.0f}')
print()
print('=' * 60)
print('📉 PRODUCTO CON MENOR TOTAL_VENTA')
print('=' * 60)
print(f'   → Producto : {producto_min}')
print(f'   → Total    : $ {valor_min:,.0f}')

============================================================
🏆 PRODUCTO CON MAYOR TOTAL_VENTA
============================================================
   → Producto : Raspberry Pi 4
   → Total    : $ 67,200,000

============================================================
📉 PRODUCTO CON MENOR TOTAL_VENTA
============================================================
   → Producto : Laptop Gamer
   → Total    : $ 300,000

---
## 📌 Punto 3 — Porcentajes y Análisis

In [13]:
# ── 3.1 IVA = 19% del Total_Venta ────────────────────────────────────────────
df['IVA'] = df['Total_Venta'] * 0.19

# ── 3.2 Ganancia_Estimada = 25% del Total_Venta ───────────────────────────────
df['Ganancia_Estimada'] = df['Total_Venta'] * 0.25

# ── 3.3 Perdida_Estimada = 0.05% del Total_Venta ─────────────────────────────
df['Perdida_Estimada'] = df['Total_Venta'] * 0.0005

print('✅ Columnas de porcentajes creadas')
display(df[['Producto', 'Total_Venta', 'IVA', 'Ganancia_Estimada', 'Perdida_Estimada']].head(10))

✅ Columnas de porcentajes creadas

,Producto,Total_Venta,IVA,Ganancia_Estimada,Perdida_Estimada
0,Laptop,14000000,2660000.0,3500000.0,7000.0
1,Mouse,1200000,228000.0,300000.0,600.0
2,Teclado,1200000,228000.0,300000.0,600.0
3,Silla,2250000,427500.0,562500.0,1125.0
4,Escritorio,2700000,513000.0,675000.0,1350.0
5,Monitor,6600000,1254000.0,1650000.0,3300.0
6,Auriculares Bluetooth,2240000,425600.0,560000.0,1120.0
7,Webcam HD,1800000,342000.0,450000.0,900.0
8,Micrófono USB,1400000,266000.0,350000.0,700.0
9,Disco Duro Externo 1TB,3200000,608000.0,800000.0,1600.0

In [14]:
# ── 3.4 Porcentaje de cada producto sobre el total general ────────────────────
total_general = df['Total_Venta'].sum()
df['Porcentaje_Ventas'] = (df['Total_Venta'] / total_general) * 100

print('=' * 60)
print('📊 PORCENTAJE DE VENTAS POR PRODUCTO (Top 15)')
print('=' * 60)
print(f'   Total general de ventas: $ {total_general:,.0f}')
print()
display(
    df[['Producto', 'Total_Venta', 'Porcentaje_Ventas']]
    .sort_values('Porcentaje_Ventas', ascending=False)
    .head(15)
    .assign(Porcentaje_Ventas=lambda x: x['Porcentaje_Ventas'].map('{:.2f}%'.format))
    .reset_index(drop=True)
)

============================================================
📊 PORCENTAJE DE VENTAS POR PRODUCTO (Top 15)
============================================================
   Total general de ventas: $ 296,410,000

                    Producto  Total_Venta Porcentaje_Ventas
0             Raspberry Pi 4     67200000            22.67%
1           Teclado Mecánico     28600000             9.65%
2                    Mini PC     16800000             5.67%
3                     Laptop     14000000             4.72%
4              Banda Fitness      9750000             3.29%
5          Smartwatch Básico      9000000             3.04%
6         Smartwatch Premium      8400000             2.83%
7              Router WiFi 6      6600000             2.23%
8                    Monitor      6600000             2.23%
9           Switch 8 Puertos      5600000             1.89%
10  Tarjeta Gráfica RTX 3060      5400000             1.82%
11              Access Point      5280000             1.78%
12       Procesador Intel i7      4800000             1.62%
13    Procesador AMD Ryzen 7      4750000             1.60%
14          Laptop Ultrabook      4500000             1.52%

In [15]:
# ── 3.5 Productos con participación > 15% ─────────────────────────────────────
productos_top = df[df['Porcentaje_Ventas'] > 15].copy()

print('=' * 60)
print('🔝 PRODUCTOS CON PARTICIPACIÓN > 15% EN VENTAS')
print('=' * 60)

if productos_top.empty:
    print('   ⚠️  Ningún producto supera el 15% del total de ventas.')
    print('   Esto indica que las ventas están bien distribuidas.')
    print()
    print('   Los 5 productos con mayor participación son:')
    display(
        df[['Producto', 'Total_Venta', 'Porcentaje_Ventas']]
        .sort_values('Porcentaje_Ventas', ascending=False)
        .head(5)
        .assign(Porcentaje_Ventas=lambda x: x['Porcentaje_Ventas'].map('{:.2f}%'.format))
        .reset_index(drop=True)
    )
else:
    display(
        productos_top[['Producto', 'Total_Venta', 'Porcentaje_Ventas']]
        .sort_values('Porcentaje_Ventas', ascending=False)
        .assign(Porcentaje_Ventas=lambda x: x['Porcentaje_Ventas'].map('{:.2f}%'.format))
        .reset_index(drop=True)
    )

============================================================
🔝 PRODUCTOS CON PARTICIPACIÓN > 15% EN VENTAS
============================================================

         Producto  Total_Venta Porcentaje_Ventas
0  Raspberry Pi 4     67200000            22.67%

---
## 📌 Punto 4 — Estadística Descriptiva

In [16]:
# ── 4.1 Media, Mediana y Moda del Precio ─────────────────────────────────────
media_precio   = df['Precio'].mean()
mediana_precio = df['Precio'].median()
moda_precio    = df['Precio'].mode()

print('=' * 60)
print('📊 ESTADÍSTICAS DE LA COLUMNA PRECIO')
print('=' * 60)
print(f'   • Media   : $ {media_precio:,.0f}')
print(f'   • Mediana : $ {mediana_precio:,.0f}')
print(f'   • Moda    : {moda_precio.values}')
print()
print('💡 Interpretación:')
print(f'   → Media ({media_precio:,.0f}): Precio promedio de todos los productos.')
print(f'   → Mediana ({mediana_precio:,.0f}): El 50% de los productos cuesta menos de este valor.')
print(f'   → Moda: El/los precio(s) que más se repite(n) en el catálogo.')

============================================================
📊 ESTADÍSTICAS DE LA COLUMNA PRECIO
============================================================
   • Media   : $ 645,250
   • Mediana : $ 350,000
   • Moda    : [280000]

💡 Interpretación:
   → Media (645,250): Precio promedio de todos los productos.
   → Mediana (350,000): El 50% de los productos cuesta menos de este valor.
   → Moda: El/los precio(s) que más se repite(n) en el catálogo.

In [17]:
# ── 4.2 Desviación estándar de Cantidad ──────────────────────────────────────
std_cantidad = df['Cantidad'].std()

print('=' * 60)
print('📊 DESVIACIÓN ESTÁNDAR DE CANTIDAD')
print('=' * 60)
print(f'   • Desviación estándar: {std_cantidad:.2f} unidades')
print(f'   • Media de Cantidad  : {df["Cantidad"].mean():.2f} unidades')
print()
print('💡 Interpretación:')
print(f'   La desviación de {std_cantidad:.2f} indica variabilidad en el stock.')
print(f'   Algunos productos tienen muchas unidades y otros pocas.')

============================================================
📊 DESVIACIÓN ESTÁNDAR DE CANTIDAD
============================================================
   • Desviación estándar: 6.19 unidades
   • Media de Cantidad  : 9.88 unidades

💡 Interpretación:
   La desviación de 6.19 indica variabilidad en el stock.
   Algunos productos tienen muchas unidades y otros pocas.

In [18]:
# ── 4.3 Máximo y mínimo de Total_Venta ───────────────────────────────────────
max_tv   = df['Total_Venta'].max()
min_tv   = df['Total_Venta'].min()
rango    = max_tv - min_tv
prod_max = df.loc[df['Total_Venta'].idxmax(), 'Producto']
prod_min = df.loc[df['Total_Venta'].idxmin(), 'Producto']

print('=' * 60)
print('📊 RANGO DE TOTAL_VENTA')
print('=' * 60)
print(f'   • Máximo : $ {max_tv:,.0f}  → {prod_max}')
print(f'   • Mínimo : $ {min_tv:,.0f}  → {prod_min}')
print(f'   • Rango  : $ {rango:,.0f}')
print()
print('💡 Interpretación:')
print(f'   El rango de $ {rango:,.0f} indica alta dispersión en el')
print(f'   desempeño de ventas entre productos.')

============================================================
📊 RANGO DE TOTAL_VENTA
============================================================
   • Máximo : $ 67,200,000  → Raspberry Pi 4
   • Mínimo : $ 300,000  → Laptop Gamer
   • Rango  : $ 66,900,000

💡 Interpretación:
   El rango de $ 66,900,000 indica alta dispersión en el
   desempeño de ventas entre productos.

---
## 📌 Punto 5 — Filtrado

In [19]:
# ── 5.1 Solo productos de Tecnología ─────────────────────────────────────────
df_tecnologia = df[df['Categoria'] == 'Tecnología'].copy()

print('=' * 60)
print('💻 PRODUCTOS DE CATEGORÍA: TECNOLOGÍA')
print('=' * 60)
print(f'   → Total tecnológicos : {len(df_tecnologia)}')
print(f'   → Total en dataset   : {len(df)}')
print()
display(df_tecnologia[['Producto', 'Precio', 'Cantidad', 'Total_Venta', 'Categoria']].reset_index(drop=True))

============================================================
💻 PRODUCTOS DE CATEGORÍA: TECNOLOGÍA
============================================================
   → Total tecnológicos : 58
   → Total en dataset   : 60

                       Producto   Precio  Cantidad  Total_Venta   Categoria
0                        Laptop  3500000         4     14000000  Tecnología
1                         Mouse    80000        15      1200000  Tecnología
2                       Teclado   120000        10      1200000  Tecnología
3                       Monitor  1100000         6      6600000  Tecnología
4         Auriculares Bluetooth   280000         8      2240000  Tecnología
5                     Webcam HD   150000        12      1800000  Tecnología
6                 Micrófono USB   200000         7      1400000  Tecnología
7        Disco Duro Externo 1TB   320000        10      3200000  Tecnología
8        Disco Duro Externo 2TB   480000         6      2880000  Tecnología
9                     SSD 500GB   280000        14      3920000  Tecnología
10                      SSD 1TB   450000         9      4050000  Tecnología
11              Memoria RAM 8GB   120000        20      2400000  Tecnología
12             Memoria RAM 16GB   220000        15      3300000  Tecnología
13     Tarjeta Gráfica GTX 1650   950000         4      3800000  Tecnología
14     Tarjeta Gráfica RTX 3060  1800000         3      5400000  Tecnología
15          Procesador Intel i5   780000         5      3900000  Tecnología
16          Procesador Intel i7  1200000         4      4800000  Tecnología
17       Procesador AMD Ryzen 5   650000         6      3900000  Tecnología
18       Procesador AMD Ryzen 7   950000         5      4750000  Tecnología
19               Placa Base ATX   380000         7      2660000  Tecnología
20         Fuente de Poder 650W   180000        10      1800000  Tecnología
21              Gabinete Gaming   250000         6      1500000  Tecnología
22                 Mouse Pad XL    35000        25       875000  Tecnología
23            Hub USB 4 Puertos    45000        18       810000  Tecnología
24            Hub USB 7 Puertos    75000        12       900000  Tecnología
25                Cable HDMI 2m    25000        30       750000  Tecnología
26                Cable HDMI 5m    45000        15       675000  Tecnología
27              Adaptador USB-C   180000         8      1440000  Tecnología
28         Cargador Inalámbrico    85000        20      1700000  Tecnología
29          Power Bank 10000mAh   160000        10      1600000  Tecnología
30          Power Bank 20000mAh    95000        18      1710000  Tecnología
31              Impresora Láser   350000         5      1750000  Tecnología
32     Impresora Multifuncional   580000         3      1740000  Tecnología
33             Escáner Portátil   220000         9      1980000  Tecnología
34                Router WiFi 6  1100000         6      6600000  Tecnología
35             Switch 8 Puertos  1400000         4      5600000  Tecnología
36                 Access Point   480000        11      5280000  Tecnología
37           Tablet 10 pulgadas   320000         8      2560000  Tecnología
38                    iPad Mini   680000         5      3400000  Tecnología
39  Teléfono Inteligente Básico    85000        20      1700000  Tecnología
40            Smartwatch Básico   750000        12      9000000  Tecnología
41           Smartwatch Premium  1200000         7      8400000  Tecnología
42                Banda Fitness   650000        15      9750000  Tecnología
43             Altavoz Portátil   350000         6      2100000  Tecnología
44           Altavoz Escritorio  1900000         2      3800000  Tecnología
45            Proyector Full HD   280000        13      3640000  Tecnología
46           Lector de Tarjetas   280000        10      2800000  Tecnología
47                    UPS 600VA   380000         8      3040000  Tecnología
48                   UPS 1200VA   350000         7      2450000  Tecnología
49             Teclado Mecánico  1300000        22     28600000  Tecnología
50             Mouse Ergonómico    95000        18      1710000  Tecnología
51                 Mouse Gaming   150000        16      2400000  Tecnología
52          Monitor 27 pulgadas   280000         5      1400000  Tecnología
53    Monitor Curvo 32 pulgadas   450000         4      1800000  Tecnología
54                 Laptop Gamer   150000         2       300000  Tecnología
55             Laptop Ultrabook  1500000         3      4500000  Tecnología
56                      Mini PC  2100000         8     16800000  Tecnología
57               Raspberry Pi 4  4800000        14     67200000  Tecnología

In [20]:
# ── 5.2 Ordenar de mayor a menor por Total_Venta ─────────────────────────────
df_ordenado = df.sort_values('Total_Venta', ascending=False).reset_index(drop=True)

print('=' * 60)
print('📋 RANKING POR TOTAL_VENTA (Mayor → Menor)')
print('=' * 60)
display(
    df_ordenado[['Producto', 'Precio', 'Cantidad', 'Total_Venta', 'Porcentaje_Ventas', 'Categoria']]
    .assign(Porcentaje_Ventas=lambda x: x['Porcentaje_Ventas'].map('{:.2f}%'.format))
)

============================================================
📋 RANKING POR TOTAL_VENTA (Mayor → Menor)
============================================================

,Producto,Precio,Cantidad,Total_Venta,Porcentaje_Ventas,Categoria
0,Raspberry Pi 4,4800000,14,67200000,22.67%,Tecnología
1,Teclado Mecánico,1300000,22,28600000,9.65%,Tecnología
2,Mini PC,2100000,8,16800000,5.67%,Tecnología
3,Laptop,3500000,4,14000000,4.72%,Tecnología
4,Banda Fitness,650000,15,9750000,3.29%,Tecnología
5,Smartwatch Básico,750000,12,9000000,3.04%,Tecnología
6,Smartwatch Premium,1200000,7,8400000,2.83%,Tecnología
7,Router WiFi 6,1100000,6,6600000,2.23%,Tecnología
8,Monitor,1100000,6,6600000,2.23%,Tecnología
9,Switch 8 Puertos,1400000,4,5600000,1.89%,Tecnología
10,Tarjeta Gráfica RTX 3060,1800000,3,5400000,1.82%,Tecnología
11,Access Point,480000,11,5280000,1.78%,Tecnología
12,Procesador Intel i7,1200000,4,4800000,1.62%,Tecnología
13,Procesador AMD Ryzen 7,950000,5,4750000,1.60%,Tecnología
14,Laptop Ultrabook,1500000,3,4500000,1.52%,Tecnología
15,SSD 1TB,450000,9,4050000,1.37%,Tecnología
16,SSD 500GB,280000,14,3920000,1.32%,Tecnología
17,Procesador AMD Ryzen 5,650000,6,3900000,1.32%,Tecnología
18,Procesador Intel i5,780000,5,3900000,1.32%,Tecnología
19,Altavoz Escritorio,1900000,2,3800000,1.28%,Tecnología
20,Tarjeta Gráfica GTX 1650,950000,4,3800000,1.28%,Tecnología
21,Proyector Full HD,280000,13,3640000,1.23%,Tecnología
22,iPad Mini,680000,5,3400000,1.15%,Tecnología
23,Memoria RAM 16GB,220000,15,3300000,1.11%,Tecnología
24,Disco Duro Externo 1TB,320000,10,3200000,1.08%,Tecnología
25,UPS 600VA,380000,8,3040000,1.03%,Tecnología
26,Disco Duro Externo 2TB,480000,6,2880000,0.97%,Tecnología
27,Lector de Tarjetas,280000,10,2800000,0.94%,Tecnología
28,Escritorio,900000,3,2700000,0.91%,Oficina
29,Placa Base ATX,380000,7,2660000,0.90%,Tecnología
30,Tablet 10 pulgadas,320000,8,2560000,0.86%,Tecnología
31,UPS 1200VA,350000,7,2450000,0.83%,Tecnología
32,Memoria RAM 8GB,120000,20,2400000,0.81%,Tecnología
33,Mouse Gaming,150000,16,2400000,0.81%,Tecnología
34,Silla,450000,5,2250000,0.76%,Oficina
35,Auriculares Bluetooth,280000,8,2240000,0.76%,Tecnología
36,Altavoz Portátil,350000,6,2100000,0.71%,Tecnología
37,Escáner Portátil,220000,9,1980000,0.67%,Tecnología
38,Webcam HD,150000,12,1800000,0.61%,Tecnología
39,Fuente de Poder 650W,180000,10,1800000,0.61%,Tecnología
40,Monitor Curvo 32 pulgadas,450000,4,1800000,0.61%,Tecnología
41,Impresora Láser,350000,5,1750000,0.59%,Tecnología
42,Impresora Multifuncional,580000,3,1740000,0.59%,Tecnología
43,Power Bank 20000mAh,95000,18,1710000,0.58%,Tecnología
44,Mouse Ergonómico,95000,18,1710000,0.58%,Tecnología
45,Cargador Inalámbrico,85000,20,1700000,0.57%,Tecnología
46,Teléfono Inteligente Básico,85000,20,1700000,0.57%,Tecnología
47,Power Bank 10000mAh,160000,10,1600000,0.54%,Tecnología
48,Gabinete Gaming,250000,6,1500000,0.51%,Tecnología
49,Adaptador USB-C,180000,8,1440000,0.49%,Tecnología
50,Micrófono USB,200000,7,1400000,0.47%,Tecnología
51,Monitor 27 pulgadas,280000,5,1400000,0.47%,Tecnología
52,Teclado,120000,10,1200000,0.40%,Tecnología
53,Mouse,80000,15,1200000,0.40%,Tecnología
54,Hub USB 7 Puertos,75000,12,900000,0.30%,Tecnología
55,Mouse Pad XL,35000,25,875000,0.30%,Tecnología
56,Hub USB 4 Puertos,45000,18,810000,0.27%,Tecnología
57,Cable HDMI 2m,25000,30,750000,0.25%,Tecnología
58,Cable HDMI 5m,45000,15,675000,0.23%,Tecnología
59,Laptop Gamer,150000,2,300000,0.10%,Tecnología

---
## 🌟 Punto Adicional — Exportar DataFrame final a Excel

In [21]:
# Exportamos el DataFrame con todas las columnas calculadas
df_final = df.sort_values('Total_Venta', ascending=False).reset_index(drop=True)

nombre_archivo = 'resultados_taller_pandas.xlsx'
df_final.to_excel(nombre_archivo, index=False, sheet_name='Análisis de Productos')

print('✅ DataFrame exportado exitosamente')
print(f'   → Archivo  : {nombre_archivo}')
print(f'   → Filas    : {len(df_final)}')
print(f'   → Columnas : {list(df_final.columns)}')

✅ DataFrame exportado exitosamente
   → Archivo  : resultados_taller_pandas.xlsx
   → Filas    : 60
   → Columnas : ['Producto', 'Precio', 'Cantidad', 'Costo_Envio', 'Categoria', 'Total_Venta', 'Costo_Total', 'IVA', 'Ganancia_Estimada', 'Perdida_Estimada', 'Porcentaje_Ventas']